# Generated by Django 4.2.13 on 2024-07-24 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id_ejercicio', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('tipo', models.EmailField(max_length=50)),
                ('puntos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Foro',
            fields=[
                ('id_foro', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Insignia',
            fields=[
                ('id_insignia', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id_logro', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id_nivel', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id_ranking', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.IntegerField()),
                ('posicion', models.CharField(max_length=50)),
                ('fecha_actualizacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Recompensa',
            fields=[
                ('id_recompensa', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('condicion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario_recompensa',
            fields=[
                ('id_usuario_recompensa', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.IntegerField()),
                ('fecha_otorgada', models.DateField()),
                ('recompensa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recompensas', to='myapp.recompensa')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_logro',
            fields=[
                ('id_usuario_logro', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.IntegerField()),
                ('fecha_completado', models.DateField()),
                ('logro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros', to='myapp.logro')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_insignia',
            fields=[
                ('id_usuario_insignia', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.IntegerField()),
                ('fecha_otorgada', models.DateField()),
                ('insignia_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insignias', to='myapp.insignia')),
            ],
        ),
        migrations.CreateModel(
            name='Participacion_foro',
            fields=[
                ('id_participacion_foro', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.IntegerField()),
                ('fecha_participacion', models.DateField()),
                ('comentario', models.CharField(max_length=50)),
                ('resultado', models.BooleanField()),
                ('foro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones_foro', to='myapp.foro')),
            ],
        ),
        migrations.AddField(
            model_name='logro',
            name='recompensa_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recompensas_logro', to='myapp.recompensa'),
        ),
        migrations.CreateModel(
            name='Intento',
            fields=[
                ('id_intento', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.IntegerField()),
                ('fecha', models.DateField()),
                ('resultado', models.BooleanField()),
                ('errores', models.IntegerField()),
                ('ejercicio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos_ejercicios', to='myapp.ejercicio')),
            ],
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='nivel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='myapp.nivel'),
        ),
    ]
