# Generated by Django 4.2.13 on 2024-08-25 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foro_respuesta',
            fields=[
                ('id_respuesta', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('autor', models.CharField(max_length=50)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('foro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='myapp.foro')),
            ],
        ),
    ]
