# Generated by Django 4.2.13 on 2024-08-31 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_foro_respuesta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejercicio',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='descripcion',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nivel',
            name='descripcion',
            field=models.TextField(max_length=50),
        ),
    ]
