# Generated by Django 4.2.13 on 2024-08-31 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_ejercicio_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='codigo',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='salida_esperada',
            field=models.TextField(blank=True, null=True),
        ),
    ]
