# Generated by Django 4.2.13 on 2024-09-01 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_ejercicio_codigo_ejercicio_salida_esperada'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='terminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='myapp.user'),
            preserve_default=False,
        ),
    ]
